### PR TITLE
fix: hardcoded realMouseMove position

### LINKED ISSUE #234: `realMouseMove()` uses hardcoded position "topLeft"
I think the `cy.realMouseMove()` command has a hardcoded position as seen below.

https://github.com/dmtrKovalenko/cypress-real-events/blob/2282480708dbf42f5899ffba1288e1c6364d0ea2/src/commands/mouseMove.ts#L29-L33

I tried to use it with `position: center` as in the code example below but the event happened in the same hardcoded `topLeft` position.

https://github.com/dmtrKovalenko/cypress-real-events/blob/e9ca39f3fe1b1e03d57728aa8b1140d98df65739/README.md?plain=1#L314

I made Cypress test cases for all Cypress positions listed here:

https://github.com/dmtrKovalenko/cypress-real-events/blob/e9ca39f3fe1b1e03d57728aa8b1140d98df65739/src/getCypressElementCoordinates.ts#L1-L10
 
Here is the pattern for my Cypress tests.:

```js
cy.get("body")
  .realMouseDown()
  .realMouseMove(20, 10, { position: "topLeft" })
  .realMouseMove(30, 20, { position: "topLeft" })
  .realMouseUp();
cy.get("body")
  .realMouseDown()
  .realMouseMove(20, 10, { position: "top" })
  .realMouseMove(30, 20, { position: "top" })
  .realMouseUp();
cy.get("body")
  .realMouseDown()
  .realMouseMove(-20, 10, { position: "topRight" })
  .realMouseMove(-30, 20, { position: "topRight" })
  .realMouseUp();
```

### Outcomes

| Ideal | Current |
|--|--|
| image | image |

Currently, the marks are all overlapping. Ideally, they should all be in different positions according to the options given to `cy.realMouseMove()`

### PR DESCRIPTION
**Pull request by drecali**
## Summary of changes
* Changed the hardcoded `topLeft` position of `cy.realMouseMove()` to `options.position`.
* Added tests for this change. The tests fail with the hardcoded position but pass with `options.position`.

Closes #234 

## Explanation:
I think the `cy.realMouseMove()` command has a hardcoded position as seen below.

https://github.com/dmtrKovalenko/cypress-real-events/blob/2282480708dbf42f5899ffba1288e1c6364d0ea2/src/commands/mouseMove.ts#L29-L33

I tried to use it with `position: center` as in the code example below but the event happened in the same hardcoded `topLeft` position.

https://github.com/dmtrKovalenko/cypress-real-events/blob/e9ca39f3fe1b1e03d57728aa8b1140d98df65739/README.md?plain=1#L314

I made Cypress test cases for all Cypress positions listed here:

https://github.com/dmtrKovalenko/cypress-real-events/blob/e9ca39f3fe1b1e03d57728aa8b1140d98df65739/src/getCypressElementCoordinates.ts#L1-L10
 
Here is the pattern for my Cypress tests.:

```js
cy.get("body")
  .realMouseDown()
  .realMouseMove(20, 10, { position: "topLeft" })
  .realMouseMove(30, 20, { position: "topLeft" })
  .realMouseUp();
cy.get("body")
  .realMouseDown()
  .realMouseMove(20, 10, { position: "top" })
  .realMouseMove(30, 20, { position: "top" })
  .realMouseUp();
cy.get("body")
  .realMouseDown()
  .realMouseMove(-20, 10, { position: "topRight" })
  .realMouseMove(-30, 20, { position: "topRight" })
  .realMouseUp();
```

### Outcomes

| `options.position` | hardcoded |
|--|--|
| image | image |

With the hardcoded position, the marks are all overlapping. Ideally, they should all be in different positions according to the position option given to `cy.realMouseMove()`

Please let me know if I missed anything.

### CODE REVIEW

File: src/commands/mouseMove.ts [hunk 1]
```diff
@@ -28,7 +28,7 @@ export async function realMouseMove(
 ) {
   const basePosition= getCypressElementCoordinates(
     subject,
-    "topLeft",
+    options.position,
```
Comment (dmtrKovalenko) [inline src/commands/mouseMove.ts:31]:
```suggestion
    options.position ?? "topLeft",
```

I think this is reasonable to have a default topLeft coordinate system and not sure somebody want's to actually use this option but I agree we need to fix it. Thanks.

**Review by dmtrKovalenko — CHANGES_REQUESTED** [review]

File: src/commands/mouseMove.ts (hunk 1 above)
Comment (drecali) [reply src/commands/mouseMove.ts]: @dmtrKovalenko 
Thank you for pointing that out and the quick response!

I noticed in another part of the repo it seems like `center` is the default coordinate. Is it OK if this default is `topLeft`, or should they be consistent?

https://github.com/dmtrKovalenko/cypress-real-events/blob/e9ca39f3fe1b1e03d57728aa8b1140d98df65739/src/getCypressElementCoordinates.ts#L167-L173

File: cypress/integration/mouse.spec.ts [hunk 2]
```diff
@@ -357,3 +357,64 @@ describe("realMouseMove", () => {
...
+describe("canvas drag with realMouseMove", () => {
+  beforeEach(() => {
+    cy.visit("./cypress/fixtures/canvas-drag-svg.html");
+  });
+  it("drags with realMouseMove in every position option", () => {
+    cy.get("body")
+      .realMouseDown()
+      .realMouseMove(20, 10)
+      .realMouseMove(30, 20)
+      .realMouseUp();
```
Comment (drecali) [inline cypress/integration/mouse.spec.ts:370]: I added this test for the default `topLeft` position in addition to the explicit `topLeft` position. We are expecting the marks to be next to each other as below.

image

Comment (dmtrKovalenko) [reply cypress/integration/mouse.spec.ts:370]: I actually don't understand how it is posisble

Comment (drecali) [reply cypress/integration/mouse.spec.ts:370]: Since `topLeft` is the default option, I thought it's good to add a test for the default `topLeft` and the explicit `topLeft`. Should I remove one of the tests or is there another issue?

Comment (drecali) [reply cypress/integration/mouse.spec.ts]: I refactored the tests I added and I think it's more clear now. Here is the logic
1. Draw `<polyline>`s with 2 points using `.realMouseMove` with all 9 explicit `positions` from Cypress 
2. Check that all `<polyline>`s are not overlapping (by `cy.click()`)
3. Draw a final `<polyline>` with `.realMouseMove` and no `position` specified. The default value of `topLeft` should cause this to overlap the first `<polyline>`.
  * Check that first and last `<polyline>`s have the same `points`
  * Check that all `<polyline>`s except for the first are not overlapping (by `cy.click()`)

Is this a reasonable testing strategy?

File: src/commands/mouseMove.ts (hunk 1 above)
Comment (dmtrKovalenko) [reply src/commands/mouseMove.ts]: Yeah for most of actions we have center as base point, but it will be strange to force people to write negative coordinated (which is still possible) for mouse moves.

Comment (drecali) [reply src/commands/mouseMove.ts]: @dmtrKovalenko Good point!

**Review by dmtrKovalenko — APPROVED** [review]
Lgtm
